Implement the UI
meaningfy-ws/rdf-fingerprinter-ws pull request #4
Opened 2020-10-23 07:16 UTC by cosletmihai

2020-10-23 07:43 UTC, costezki approved these changes

2020-10-23 21:49 UTC, costezki requested changes
Well done! 
Just, we need to figure out what to do with external binaries (a new makefile install target would be a good workaround)

2020-10-23 21:49 UTC, costezki commented on fingerprinter/config.py
> +RDF_FINGERPRINTER_UI_LOCATION = os.environ.get('RDF_FINGERPRINTER_UI_LOCATION', 'http://localhost')
I think we mean something different than location here. Is that host or domain name?
We should have a similar variable in the other project.

2020-10-23 21:49 UTC, costezki commented on fingerprinter/entrypoints/ui/templates/base.html
> +   <nav class="navbar navbar-expand-lg navbar-light bg-light deep-purple lighten-2">
https://en.wikipedia.org/wiki/Deep_Purple

2020-10-23 21:49 UTC, costezki commented on scripts/commands.py
> +def populate_fuseki():
probably it is better to learn how to use the HTTP graph store protocol:
https://www.w3.org/TR/sparql11-http-rdf-update/

An example of upload to Fuseki using that protocol is found here

https://github.com/meaningfy-ws/rdf-fingerprinter/blob/master/Makefile
```
fuseki-create-test-dbs:
	@ echo "$(BUILD_PRINT)Building dummy 'dev' dataset at http://localhost:$(if $(RDF_FINGERPRINTER_FUSEKI_PORT),$(RDF_FINGERPRINTER_FUSEKI_PORT),unknown port)/$$/datasets"
	@ sleep 2
	@ curl --anyauth --user 'admin:$(RDF_FINGERPRINTER_FUSEKI_ADMIN_PASSWORD)' -d 'dbType=mem&dbName=dev'  'http://localhost:$(RDF_FINGERPRINTER_FUSEKI_PORT)/$$/datasets'
	@ curl -X POST -H content-type:application/rdf+xml -T ./tests/test_data/treaties-source-ap.rdf -G http://localhost:$(RDF_FINGERPRINTER_FUSEKI_PORT)/dev/data

```

2020-10-23 21:49 UTC, costezki commented on tests/conftest.py
> +def browser():
Nieace!

2020-10-23 21:49 UTC, costezki commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
what exactly?

2020-10-23 21:49 UTC, costezki commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
really? :D

2020-10-23 21:49 UTC, costezki commented on tests/conftest.py
> +    path_to_driver = str(Path(__file__).parent / 'resources/chromedriver')
please do not host the chromedriver in the project. Rule of thumb "if we have an external binary in the code, something smells here"
Workaround: write a dev-setup script, which downloads and installs it locally, from a known location.

2020-10-24 07:24 UTC, cosletmihai commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
nobody knows...

 Dragoș trebuie să pună ceva pe paginile de flask după ce vine ceva cu success (asta am discutat cu Laur)

2020-10-24 07:24 UTC, cosletmihai commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
yes :D

2020-10-24 08:52 UTC, cosletmihai commented on fingerprinter/entrypoints/ui/templates/base.html
> +   <nav class="navbar navbar-expand-lg navbar-light bg-light deep-purple lighten-2">
yes, great band :D

2020-10-24 09:28 UTC, costezki commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
The easiest solution here would be to redirect to another page. Then it will be consistent and predictable.

2020-10-24 09:48 UTC, cosletmihai commented on tests/features/ui_fingerprinting.feature
> +    Then something happens
I'd recommend you shoot a message to flask development team and ask them to implement the functionality to send file and redirect in the same action :D

2020-10-24 10:53 UTC, costezki approved these changes

2020-10-25 07:16 UTC, cosletmihai commented
`chromidriver` will be removed from project with the implementation of this [task](https://meaningfy.atlassian.net/browse/MDR-273?atlOrigin=eyJpIjoiZmI0ZjFkYTk2MmFjNGY3OGE2OGU5MzBhYWYzYzIwMGQiLCJwIjoiaiJ9)

2020-10-25 11:20 UTC, costezki approved these changes

2020-10-25 16:10 UTC, merged